//
//  StyleKit.swift
//  ProjectName
//
//  Created by jwzhuang on 2016/11/25.
//  Copyright (c) 2016 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class StyleKit : NSObject {
    
    //// Drawing Methods
    
    public class func drawNotice(_ frame: CGRect = CGRect(x: 0, y: 0, width: 100, height: 100), text: String = "", textSize: CGFloat = 12) {
        //// General Declarations
        if let context = UIGraphicsGetCurrentContext(){
            
            //// Oval Drawing
            let ovalRect = CGRect(x: frame.minX + 1, y: frame.minY + 1, width: frame.width - 2, height: frame.height - 2)
            let ovalPath = UIBezierPath(ovalIn: ovalRect)
            UIColor.red.setFill()
            ovalPath.fill()
            let ovalStyle = NSMutableParagraphStyle()
            ovalStyle.alignment = .center
            
            let ovalFontAttributes = [NSFontAttributeName: UIFont(name: "HelveticaNeue", size: textSize)!, NSForegroundColorAttributeName: UIColor.white, NSParagraphStyleAttributeName: ovalStyle]
            
            let ovalTextHeight: CGFloat = NSString(string: text).boundingRect(with: CGSize(width: ovalRect.width, height: CGFloat.infinity), options: NSStringDrawingOptions.usesLineFragmentOrigin, attributes: ovalFontAttributes, context: nil).size.height
            context.saveGState()
            context.clip(to: ovalRect)
            NSString(string: text).draw(in: CGRect(x: ovalRect.minX, y: ovalRect.minY + (ovalRect.height - ovalTextHeight) / 2, width: ovalRect.width, height: ovalTextHeight), withAttributes: ovalFontAttributes)
            context.restoreGState()
        }
    }
}
